- name: create config using netbox
  connection: local
  hosts: device_role_router
  gather_facts: False
  
  tasks:
  - name: "Generate configs using data obtained from netbox"
    template:
    src: "./templates/config_template.j2"
    dest: "./output/{{ inventory_hostname }}.cfg"
    lstrip_blocks: yes
    
